import type { TemplateId, ResumeSettings } from '@/lib/store/types'
import type { ComponentType } from 'react'
import type { Resume } from '@/lib/store/types'
import { MasterTemplate } from './MasterTemplate'

// Registry — add new templates here only
export const TEMPLATE_META: Record<TemplateId, { label: string; description: string }> = {
  modern:  { label: 'Modern',  description: 'Professional two-column layout with clean lines and balanced accents' },
  classic: { label: 'Classic', description: 'Timeless single-column design with elegant serif typography and subtle highlights' },
  minimal: { label: 'Minimal', description: 'Zen-like simplicity focusing on content with maximum whitespace and no distractions' },
  crisp:   { label: 'Crisp',   description: 'Dynamic mixed-grid layout featuring unique vertical accent bars' },
  tokyo:   { label: 'Tokyo',   description: 'Bold, high-energy design with vivid iconography and a strong sidebar presence' },
  elite:   { label: 'Elite',   description: 'Executive-level sophistication with premium serif fonts and distinctive top-bottom borders' },
  blocks:  { label: 'Blocks',  description: 'Highly structured grid using background blocks to define clear visual hierarchy' },
  dublin:  { label: 'Dublin',  description: 'Contemporary reversed sidebar layout optimized for readability and flow' },
  london:  { label: 'London',  description: 'Prestigious serif design with delicate lines and a authoritative single-column layout' },
  berlin:  { label: 'Berlin',  description: 'Modern European aesthetic with knockout icons and high-contrast elements' },
  oslo:    { label: 'Oslo',    description: 'Warm two-column layout with a tinted sidebar and skills shown as rounded pills' },
  zurich:  { label: 'Zurich',  description: 'Precise single-column report with boxed headings, a contact grid and rated skills' },
  milano:  { label: 'Milano',  description: 'Editorial mixed layout with dates on the left and proficiency dots beside each skill' },
  seoul:   { label: 'Seoul',   description: 'Compact reversed sidebar with a stacked contact block and a multi-column skills grid' },
  aspen:   { label: 'Aspen',   description: 'Photo layout with the name, photo and contact details in a tinted sidebar' },
  vega:    { label: 'Vega',    description: 'Compact single column that fits a long history on one page' },
  lumen:   { label: 'Lumen',   description: 'Spacious centred layout that gives a first-job resume room to breathe' },
  atlas:   { label: 'Atlas',   description: 'Full-bleed colour header band over a two-column body with rated skills' },
  sierra:  { label: 'Sierra',  description: 'Creative mixed grid with a tinted sidebar, knockout icons and skill pills' },
  nova:    { label: 'Nova',    description: 'Executive serif page with hairline rules and levelled skills' },
  custom:  { label: 'Custom',  description: 'Your unique vision — fully adjustable settings for a bespoke experience' },
}

export { MasterTemplate, TemplateFooter } from './MasterTemplate'
export interface TemplateProps {
  resume: Resume
  pads?: number[]
  hideFooter?: boolean
  isMeasurement?: boolean
}

// All templates now use the MasterTemplate, but with different initial settings
export async function getTemplateComponent(
  _id: TemplateId
): Promise<ComponentType<TemplateProps>> {
  return MasterTemplate
}

/**
 * Returns the setting overrides for a specific template preset.
 * When a user clicks a template, we apply these settings to their resume.
 */
// Shared color reset — always apply when switching templates so multi-mode
// overrides don't bleed through. headingColor matches accentColor.
function colorReset(accent: string) {
  return {
    accentColor:     accent,
    colorMode:       'basic'   as const,
    headingColor:    accent,
    textColor:       '#1a1a1a',
    subtitleColor:   '#4a5568',
    dateColor:       '#4a5568',
    backgroundColor: '#ffffff',
    // Layout choices a preset makes that others don't mention; reset them so
    // switching away from a sidebar-header template doesn't keep that layout.
    headerLayout:    'top'     as const,
    sidebarTheme:    'none'    as const,
  }
}

export function getTemplateSettings(id: TemplateId): Partial<ResumeSettings> {
  switch (id) {
    case 'modern':
      return {
        ...colorReset('#1e3a5f'),
        themeColorStyle:              'basic',
        applyAccentName:              true,
        applyAccentJobTitle:          true,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   false,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        columnLayout:                 'two',
        columnReverse:                false,
        headerAlignment:              'left',
        headerArrangement:            'verticalBar',
        sectionHeadingStyle:          'underline',
        sectionHeadingSize:           'M',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'none',
        nameSize:                     'L',
        nameBold:                     true,
        fontFamily:                   'Inter',
        fontSize:                     10.5,
        lineHeight:                   1.45,
        marginHorizontal:             18,
        marginVertical:               12,
        entrySpacing:                 1.0,
      }
    case 'classic':
      return {
        ...colorReset('#111111'),
        themeColorStyle:              'advanced',
        applyAccentName:              false,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   false,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         false,
        columnLayout:                 'one',
        columnReverse:                false,
        headerAlignment:              'center',
        headerArrangement:            'verticalBar',
        sectionHeadingStyle:          'underline',
        sectionHeadingSize:           'S',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'none',
        nameSize:                     'XL',
        nameBold:                     true,
        fontFamily:                   'Merriweather',
        fontSize:                     10,
        lineHeight:                   1.5,
        marginHorizontal:             20,
        marginVertical:               14,
        entrySpacing:                 1.0,
      }
    case 'minimal':
      return {
        ...colorReset('#333333'),
        themeColorStyle:              'basic',
        applyAccentName:              false,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          false,
        applyAccentHeadingLine:       false,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   false,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         false,
        columnLayout:                 'one',
        columnReverse:                false,
        headerAlignment:              'left',
        headerArrangement:            'bullet',
        sectionHeadingStyle:          'none',
        sectionHeadingSize:           'M',
        sectionHeadingCapitalization: 'none',
        sectionHeadingIcon:           'none',
        nameSize:                     'M',
        nameBold:                     false,
        fontFamily:                   'Inter',
        fontSize:                     10.5,
        lineHeight:                   1.6,
        marginHorizontal:             24,
        marginVertical:               18,
        entrySpacing:                 1.1,
      }
    case 'crisp':
      return {
        ...colorReset('#059669'),
        themeColorStyle:              'basic',
        applyAccentName:              true,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       true,
        applyAccentDotsBarsBubbles:   false,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        columnLayout:                 'mix',
        columnReverse:                false,
        headerAlignment:              'left',
        headerArrangement:            'verticalBar',
        sectionHeadingStyle:          'left-bar',
        sectionHeadingSize:           'S',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'none',
        nameSize:                     'L',
        nameBold:                     true,
        fontFamily:                   'Lato',
        fontSize:                     10.5,
        lineHeight:                   1.45,
        marginHorizontal:             18,
        marginVertical:               12,
        entrySpacing:                 0.95,
      }
    case 'tokyo':
      return {
        ...colorReset('#dc2626'),
        themeColorStyle:              'basic',
        applyAccentName:              true,
        applyAccentJobTitle:          true,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       true,
        applyAccentDotsBarsBubbles:   true,
        applyAccentDates:             true,
        applyAccentEntrySubtitle:     true,
        applyAccentLinkIcons:         true,
        columnLayout:                 'two',
        columnReverse:                false,
        headerAlignment:              'center',
        headerArrangement:            'bullet',
        sectionHeadingStyle:          'background',
        sectionHeadingSize:           'L',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'filled',
        sectionHeadingIconSize:       1.0,
        nameSize:                     'XL',
        nameBold:                     true,
        fontFamily:                   'Roboto',
        fontSize:                     10,
        lineHeight:                   1.4,
        marginHorizontal:             16,
        marginVertical:               12,
        entrySpacing:                 0.9,
      }
    case 'elite':
      return {
        ...colorReset('#18181b'),
        themeColorStyle:              'border',
        applyAccentName:              false,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          false,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   true,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        columnLayout:                 'one',
        columnReverse:                false,
        headerAlignment:              'right',
        headerArrangement:            'verticalBar',
        sectionHeadingStyle:          'top-bottom',
        sectionHeadingSize:           'XL',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingLineThickness:  1,
        sectionHeadingIcon:           'none',
        nameSize:                     'XL',
        nameBold:                     true,
        fontFamily:                   'Playfair Display',
        fontSize:                     10,
        lineHeight:                   1.5,
        marginHorizontal:             22,
        marginVertical:               16,
        entrySpacing:                 1.1,
      }
    case 'blocks':
      return {
        ...colorReset('#2563eb'),
        themeColorStyle:              'basic',
        applyAccentName:              true,
        applyAccentJobTitle:          true,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   false,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        columnLayout:                 'mix',
        columnReverse:                false,
        headerAlignment:              'left',
        headerArrangement:            'bullet',
        sectionHeadingStyle:          'background',
        sectionHeadingSize:           'L',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'none',
        nameSize:                     'XL',
        nameBold:                     true,
        fontFamily:                   'Inter',
        fontSize:                     10.5,
        lineHeight:                   1.5,
        marginHorizontal:             20,
        marginVertical:               14,
        entrySpacing:                 1.1,
      }
    case 'dublin':
      return {
        ...colorReset('#0369a1'),
        themeColorStyle:              'basic',
        applyAccentName:              true,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   false,
        applyAccentDates:             true,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        columnLayout:                 'two',
        columnReverse:                true,
        headerAlignment:              'left',
        headerArrangement:            'verticalBar',
        sectionHeadingStyle:          'underline',
        sectionHeadingSize:           'M',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'none',
        nameSize:                     'XL',
        nameBold:                     true,
        fontFamily:                   'Inter',
        fontSize:                     10,
        lineHeight:                   1.4,
        marginHorizontal:             16,
        marginVertical:               12,
        entrySpacing:                 0.9,
      }
    case 'london':
      return {
        ...colorReset('#111111'),
        themeColorStyle:              'advanced',
        applyAccentName:              true,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          false,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   true,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        columnLayout:                 'one',
        columnReverse:                false,
        headerAlignment:              'center',
        headerArrangement:            'bullet',
        sectionHeadingStyle:          'top-bottom',
        sectionHeadingSize:           'L',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingLineThickness:  0.5,
        sectionHeadingIcon:           'none',
        nameSize:                     'XXL',
        nameBold:                     true,
        fontFamily:                   'Playfair Display',
        fontSize:                     11,
        lineHeight:                   1.5,
        marginHorizontal:             24,
        marginVertical:               20,
        entrySpacing:                 1.2,
      }
    case 'berlin':
      return {
        ...colorReset('#000000'),
        themeColorStyle:              'basic',
        applyAccentName:              true,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   true,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        columnLayout:                 'mix',
        columnReverse:                false,
        headerAlignment:              'left',
        headerArrangement:            'verticalBar',
        sectionHeadingStyle:          'background',
        sectionHeadingSize:           'S',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'knockout',
        sectionHeadingIconSize:       0.8,
        nameSize:                     'XL',
        nameBold:                     true,
        fontFamily:                   'Roboto',
        fontSize:                     10,
        lineHeight:                   1.4,
        marginHorizontal:             18,
        marginVertical:               14,
        entrySpacing:                 1.0,
      }
    // The presets below deliberately exercise the settings the older templates
    // all leave at their defaults — skillDisplay, entryLayout,
    // detailsArrangement, sidebarTheme, subtitlePlacement — so that picking a
    // template changes the structure of the page, not just its colour and font.
    case 'oslo':
      return {
        ...colorReset('#b45309'),
        themeColorStyle:              'basic',
        applyAccentName:              true,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       false,
        applyAccentHeaderIcons:       true,
        applyAccentDotsBarsBubbles:   true,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        columnLayout:                 'two',
        columnReverse:                false,
        columnWidthMode:              'manual',
        columnWidth:                  34,
        sidebarTheme:                 'accent',
        headerAlignment:              'left',
        headerArrangement:            'bullet',
        detailsArrangement:           'wrap',
        sectionHeadingStyle:          'none',
        sectionHeadingSize:           'M',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'none',
        skillDisplay:                 'bubble',
        entryLayout:                  'date-location-right',
        nameSize:                     'L',
        nameBold:                     true,
        fontFamily:                   'Raleway',
        fontSize:                     10.5,
        lineHeight:                   1.5,
        marginHorizontal:             18,
        marginVertical:               14,
        entrySpacing:                 1.05,
      }
    case 'zurich':
      return {
        ...colorReset('#334155'),
        themeColorStyle:              'basic',
        applyAccentName:              false,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   false,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         false,
        columnLayout:                 'one',
        columnReverse:                false,
        headerAlignment:              'left',
        headerArrangement:            'none',
        detailsArrangement:           'grid',
        detailsTextAlignment:         'left',
        sectionHeadingStyle:          'box',
        sectionHeadingSize:           'S',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingLineThickness:  0.75,
        sectionHeadingIcon:           'none',
        skillDisplay:                 'level',
        entryLayout:                  'date-location-right',
        subtitlePlacement:            'next-line',
        nameSize:                     'L',
        nameBold:                     true,
        fontFamily:                   'IBM Plex Serif',
        fontSize:                     10,
        lineHeight:                   1.45,
        marginHorizontal:             20,
        marginVertical:               16,
        entrySpacing:                 1.0,
      }
    case 'milano':
      return {
        ...colorReset('#9d174d'),
        themeColorStyle:              'basic',
        applyAccentName:              true,
        applyAccentJobTitle:          true,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   true,
        applyAccentDates:             true,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        columnLayout:                 'mix',
        columnReverse:                false,
        headerAlignment:              'center',
        headerArrangement:            'bullet',
        detailsArrangement:           'wrap',
        sectionHeadingStyle:          'overline',
        sectionHeadingSize:           'M',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'none',
        skillDisplay:                 'dots',
        entryLayout:                  'date-location-left',
        subtitleStyle:                'italic',
        nameSize:                     'XL',
        nameBold:                     true,
        fontFamily:                   'Lato',
        fontSize:                     10,
        lineHeight:                   1.5,
        marginHorizontal:             20,
        marginVertical:               16,
        entrySpacing:                 1.1,
      }
    case 'seoul':
      return {
        ...colorReset('#4338ca'),
        themeColorStyle:              'basic',
        applyAccentName:              true,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       true,
        applyAccentDotsBarsBubbles:   false,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     true,
        applyAccentLinkIcons:         true,
        columnLayout:                 'two',
        columnReverse:                true,
        columnWidthMode:              'manual',
        columnWidth:                  30,
        headerAlignment:              'left',
        headerArrangement:            'none',
        detailsArrangement:           'column',
        detailsPosition:              'beside',
        detailsTextAlignment:         'right',
        sectionHeadingStyle:          'left-bar',
        sectionHeadingSize:           'S',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'none',
        skillDisplay:                 'grid',
        skillColumns:                 2,
        entryLayout:                  'date-content-location',
        subtitlePlacement:            'same-line',
        nameSize:                     'L',
        nameBold:                     true,
        fontFamily:                   'Source Sans Pro',
        fontSize:                     10,
        lineHeight:                   1.4,
        marginHorizontal:             16,
        marginVertical:               12,
        entrySpacing:                 0.95,
      }
    // ── Second wave ─────────────────────────────────────────────────────────
    // Presets for the resume shapes the set above didn't cover: photo, compact,
    // first-job, header band, creative and executive.
    // Photo layout: the header, photo and contact details sit at the top of a tinted sidebar.
    case 'aspen':
      return {
        ...colorReset('#3f6b54'),
        applyAccentName:              true,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       true,
        applyAccentDotsBarsBubbles:   true,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        themeColorStyle:              'basic',
        columnLayout:                 'two',
        columnReverse:                true,
        columnWidthMode:              'manual',
        columnWidth:                  33,
        sidebarTheme:                 'accent',
        headerLayout:                 'sidebar',
        headerAlignment:              'center',
        headerArrangement:            'none',
        detailsArrangement:           'column',
        photoEnabled:                 true,
        photoShape:                   'circle',
        photoSize:                    'XL',
        photoPosition:                'top',
        photoBorderStyle:             'none',
        contactIcons:                 true,
        contactIconStyle:             'none',
        sectionHeadingStyle:          'underline',
        sectionHeadingSize:           'M',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingLineThickness:  0.75,
        sectionHeadingIcon:           'none',
        skillDisplay:                 'bubble',
        entryLayout:                  'date-location-right',
        subtitlePlacement:            'next-line',
        nameSize:                     'L',
        nameBold:                     true,
        fontFamily:                   'Lato',
        fontSize:                     10,
        lineHeight:                   1.45,
        marginHorizontal:             16,
        marginVertical:               14,
        entrySpacing:                 1,
      }
    // Compact: dense single column that fits a long history on one page.
    case 'vega':
      return {
        ...colorReset('#1f2937'),
        applyAccentName:              false,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   false,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         false,
        themeColorStyle:              'basic',
        columnLayout:                 'one',
        columnReverse:                false,
        headerAlignment:              'left',
        headerArrangement:            'verticalBar',
        detailsArrangement:           'wrap',
        sectionHeadingStyle:          'underline',
        sectionHeadingSize:           'S',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingLineThickness:  0.75,
        sectionHeadingIcon:           'none',
        skillDisplay:                 'compact',
        entryLayout:                  'date-location-right',
        subtitlePlacement:            'same-line',
        subtitleStyle:                'italic',
        nameSize:                     'M',
        nameBold:                     true,
        fontFamily:                   'Source Sans Pro',
        fontSize:                     9.5,
        lineHeight:                   1.3,
        marginHorizontal:             14,
        marginVertical:               10,
        entrySpacing:                 0.75,
        sectionSpacing:               0.85,
      }
    // Spacious: generous type and spacing so a short first-job resume fills the page.
    case 'lumen':
      return {
        ...colorReset('#0f766e'),
        applyAccentName:              true,
        applyAccentJobTitle:          true,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       true,
        applyAccentDotsBarsBubbles:   true,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     true,
        applyAccentLinkIcons:         true,
        themeColorStyle:              'basic',
        columnLayout:                 'one',
        columnReverse:                false,
        headerAlignment:              'center',
        headerArrangement:            'bullet',
        detailsArrangement:           'wrap',
        sectionHeadingStyle:          'overline',
        sectionHeadingSize:           'M',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingLineThickness:  1,
        sectionHeadingIcon:           'none',
        skillDisplay:                 'bubble',
        entryLayout:                  'date-location-right',
        subtitlePlacement:            'next-line',
        nameSize:                     'XL',
        nameBold:                     true,
        fontFamily:                   'Raleway',
        fontSize:                     11,
        lineHeight:                   1.6,
        marginHorizontal:             22,
        marginVertical:               18,
        entrySpacing:                 1.25,
        sectionSpacing:               1.2,
      }
    // Header band: a full-bleed accent header over a two-column body.
    case 'atlas':
      return {
        ...colorReset('#1e3a8a'),
        applyAccentName:              false,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       true,
        applyAccentDotsBarsBubbles:   true,
        applyAccentDates:             true,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        themeColorStyle:              'advanced',
        columnLayout:                 'two',
        columnReverse:                false,
        columnWidthMode:              'manual',
        columnWidth:                  31,
        headerAlignment:              'left',
        headerArrangement:            'none',
        detailsArrangement:           'grid',
        detailsTextAlignment:         'left',
        sectionHeadingStyle:          'left-bar',
        sectionHeadingSize:           'S',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'none',
        skillDisplay:                 'dots',
        entryLayout:                  'date-location-right',
        subtitlePlacement:            'next-line',
        nameSize:                     'XL',
        nameBold:                     true,
        fontFamily:                   'Inter',
        fontSize:                     10,
        lineHeight:                   1.45,
        marginHorizontal:             18,
        marginVertical:               14,
        entrySpacing:                 1,
      }
    // Creative: mixed grid, tinted sidebar, knockout icons and skill pills.
    case 'sierra':
      return {
        ...colorReset('#c2410c'),
        applyAccentName:              true,
        applyAccentJobTitle:          true,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       true,
        applyAccentDotsBarsBubbles:   true,
        applyAccentDates:             true,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        themeColorStyle:              'basic',
        columnLayout:                 'mix',
        columnReverse:                false,
        columnWidthMode:              'manual',
        columnWidth:                  32,
        sidebarTheme:                 'accent',
        headerAlignment:              'left',
        headerArrangement:            'bullet',
        detailsArrangement:           'wrap',
        sectionHeadingStyle:          'background',
        sectionHeadingSize:           'S',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'knockout',
        sectionHeadingIconSize:       0.9,
        skillDisplay:                 'bubble',
        entryLayout:                  'date-content-location',
        subtitlePlacement:            'same-line',
        nameSize:                     'XXL',
        nameBold:                     true,
        fontFamily:                   'Roboto',
        fontSize:                     10,
        lineHeight:                   1.45,
        marginHorizontal:             16,
        marginVertical:               12,
        entrySpacing:                 0.95,
      }
    // Executive: centred serif page with hairline rules and rated skills.
    case 'nova':
      return {
        ...colorReset('#0c4a6e'),
        applyAccentName:              false,
        applyAccentJobTitle:          true,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       false,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   true,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     true,
        applyAccentLinkIcons:         false,
        themeColorStyle:              'basic',
        columnLayout:                 'one',
        columnReverse:                false,
        headerAlignment:              'center',
        headerArrangement:            'verticalBar',
        detailsArrangement:           'wrap',
        sectionHeadingStyle:          'top-bottom',
        sectionHeadingSize:           'M',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingLineThickness:  0.5,
        sectionHeadingIcon:           'none',
        skillDisplay:                 'level',
        entryLayout:                  'date-location-right',
        subtitlePlacement:            'next-line',
        subtitleStyle:                'italic',
        nameSize:                     'XXL',
        nameBold:                     true,
        fontFamily:                   'IBM Plex Serif',
        fontSize:                     10.5,
        lineHeight:                   1.5,
        marginHorizontal:             22,
        marginVertical:               16,
        entrySpacing:                 1.1,
      }
    default:
      return {}
  }
}
