import type { TemplateId, ResumeSettings } from '@/lib/store/types'
import type { ComponentType } from 'react'
import type { Resume } from '@/lib/store/types'
import { MasterTemplate } from './MasterTemplate'

// Registry — add new templates here only
export const TEMPLATE_META: Record<TemplateId, { label: string; description: string }> = {
  modern:  { label: 'Modern',  description: 'Professional two-column layout with clean lines and balanced accents' },
  classic: { label: 'Classic', description: 'Timeless single-column design with elegant serif typography and subtle highlights' },
  minimal: { label: 'Minimal', description: 'Zen-like simplicity focusing on content with maximum whitespace and no distractions' },
  crisp:   { label: 'Crisp',   description: 'Dynamic mixed-grid layout featuring unique vertical accent bars' },
  tokyo:   { label: 'Tokyo',   description: 'Bold, high-energy design with vivid iconography and a strong sidebar presence' },
  elite:   { label: 'Elite',   description: 'Executive-level sophistication with premium serif fonts and distinctive top-bottom borders' },
  blocks:  { label: 'Blocks',  description: 'Highly structured grid using background blocks to define clear visual hierarchy' },
  dublin:  { label: 'Dublin',  description: 'Contemporary reversed sidebar layout optimized for readability and flow' },
  london:  { label: 'London',  description: 'Prestigious serif design with delicate lines and a authoritative single-column layout' },
  berlin:  { label: 'Berlin',  description: 'Modern European aesthetic with knockout icons and high-contrast elements' },
  custom:  { label: 'Custom',  description: 'Your unique vision — fully adjustable settings for a bespoke experience' },
}

export { MasterTemplate, TemplateFooter } from './MasterTemplate'
export interface TemplateProps {
  resume: Resume
  pads?: number[]
  hideFooter?: boolean
  isMeasurement?: boolean
}

// All templates now use the MasterTemplate, but with different initial settings
export async function getTemplateComponent(
  _id: TemplateId
): Promise<ComponentType<TemplateProps>> {
  return MasterTemplate
}

/**
 * Returns the setting overrides for a specific template preset.
 * When a user clicks a template, we apply these settings to their resume.
 */
// Shared color reset — always apply when switching templates so multi-mode
// overrides don't bleed through. headingColor matches accentColor.
function colorReset(accent: string) {
  return {
    accentColor:     accent,
    colorMode:       'basic'   as const,
    headingColor:    accent,
    textColor:       '#1a1a1a',
    subtitleColor:   '#4a5568',
    dateColor:       '#4a5568',
    backgroundColor: '#ffffff',
  }
}

export function getTemplateSettings(id: TemplateId): Partial<ResumeSettings> {
  switch (id) {
    case 'modern':
      return {
        ...colorReset('#1e3a5f'),
        themeColorStyle:              'basic',
        applyAccentName:              true,
        applyAccentJobTitle:          true,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   false,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        columnLayout:                 'two',
        columnReverse:                false,
        headerAlignment:              'left',
        headerArrangement:            'verticalBar',
        sectionHeadingStyle:          'underline',
        sectionHeadingSize:           'M',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'none',
        nameSize:                     'L',
        nameBold:                     true,
        fontFamily:                   'Inter',
        fontSize:                     10.5,
        lineHeight:                   1.45,
        marginHorizontal:             18,
        marginVertical:               12,
        entrySpacing:                 1.0,
      }
    case 'classic':
      return {
        ...colorReset('#111111'),
        themeColorStyle:              'advanced',
        applyAccentName:              false,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   false,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         false,
        columnLayout:                 'one',
        columnReverse:                false,
        headerAlignment:              'center',
        headerArrangement:            'verticalBar',
        sectionHeadingStyle:          'underline',
        sectionHeadingSize:           'S',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'none',
        nameSize:                     'XL',
        nameBold:                     true,
        fontFamily:                   'Merriweather',
        fontSize:                     10,
        lineHeight:                   1.5,
        marginHorizontal:             20,
        marginVertical:               14,
        entrySpacing:                 1.0,
      }
    case 'minimal':
      return {
        ...colorReset('#333333'),
        themeColorStyle:              'basic',
        applyAccentName:              false,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          false,
        applyAccentHeadingLine:       false,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   false,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         false,
        columnLayout:                 'one',
        columnReverse:                false,
        headerAlignment:              'left',
        headerArrangement:            'bullet',
        sectionHeadingStyle:          'none',
        sectionHeadingSize:           'M',
        sectionHeadingCapitalization: 'none',
        sectionHeadingIcon:           'none',
        nameSize:                     'M',
        nameBold:                     false,
        fontFamily:                   'Inter',
        fontSize:                     10.5,
        lineHeight:                   1.6,
        marginHorizontal:             24,
        marginVertical:               18,
        entrySpacing:                 1.1,
      }
    case 'crisp':
      return {
        ...colorReset('#059669'),
        themeColorStyle:              'basic',
        applyAccentName:              true,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       true,
        applyAccentDotsBarsBubbles:   false,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        columnLayout:                 'mix',
        columnReverse:                false,
        headerAlignment:              'left',
        headerArrangement:            'verticalBar',
        sectionHeadingStyle:          'left-bar',
        sectionHeadingSize:           'S',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'none',
        nameSize:                     'L',
        nameBold:                     true,
        fontFamily:                   'Lato',
        fontSize:                     10.5,
        lineHeight:                   1.45,
        marginHorizontal:             18,
        marginVertical:               12,
        entrySpacing:                 0.95,
      }
    case 'tokyo':
      return {
        ...colorReset('#dc2626'),
        themeColorStyle:              'basic',
        applyAccentName:              true,
        applyAccentJobTitle:          true,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       true,
        applyAccentDotsBarsBubbles:   true,
        applyAccentDates:             true,
        applyAccentEntrySubtitle:     true,
        applyAccentLinkIcons:         true,
        columnLayout:                 'two',
        columnReverse:                false,
        headerAlignment:              'center',
        headerArrangement:            'bullet',
        sectionHeadingStyle:          'background',
        sectionHeadingSize:           'L',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'filled',
        sectionHeadingIconSize:       1.0,
        nameSize:                     'XL',
        nameBold:                     true,
        fontFamily:                   'Roboto',
        fontSize:                     10,
        lineHeight:                   1.4,
        marginHorizontal:             16,
        marginVertical:               12,
        entrySpacing:                 0.9,
      }
    case 'elite':
      return {
        ...colorReset('#18181b'),
        themeColorStyle:              'border',
        applyAccentName:              false,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          false,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   true,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        columnLayout:                 'one',
        columnReverse:                false,
        headerAlignment:              'right',
        headerArrangement:            'verticalBar',
        sectionHeadingStyle:          'top-bottom',
        sectionHeadingSize:           'XL',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingLineThickness:  1,
        sectionHeadingIcon:           'none',
        nameSize:                     'XL',
        nameBold:                     true,
        fontFamily:                   'Playfair Display',
        fontSize:                     10,
        lineHeight:                   1.5,
        marginHorizontal:             22,
        marginVertical:               16,
        entrySpacing:                 1.1,
      }
    case 'blocks':
      return {
        ...colorReset('#2563eb'),
        themeColorStyle:              'basic',
        applyAccentName:              true,
        applyAccentJobTitle:          true,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   false,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        columnLayout:                 'mix',
        columnReverse:                false,
        headerAlignment:              'left',
        headerArrangement:            'bullet',
        sectionHeadingStyle:          'background',
        sectionHeadingSize:           'L',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'none',
        nameSize:                     'XL',
        nameBold:                     true,
        fontFamily:                   'Inter',
        fontSize:                     10.5,
        lineHeight:                   1.5,
        marginHorizontal:             20,
        marginVertical:               14,
        entrySpacing:                 1.1,
      }
    case 'dublin':
      return {
        ...colorReset('#0369a1'),
        themeColorStyle:              'basic',
        applyAccentName:              true,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   false,
        applyAccentDates:             true,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        columnLayout:                 'two',
        columnReverse:                true,
        headerAlignment:              'left',
        headerArrangement:            'verticalBar',
        sectionHeadingStyle:          'underline',
        sectionHeadingSize:           'M',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'none',
        nameSize:                     'XL',
        nameBold:                     true,
        fontFamily:                   'Inter',
        fontSize:                     10,
        lineHeight:                   1.4,
        marginHorizontal:             16,
        marginVertical:               12,
        entrySpacing:                 0.9,
      }
    case 'london':
      return {
        ...colorReset('#111111'),
        themeColorStyle:              'advanced',
        applyAccentName:              true,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          false,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   true,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        columnLayout:                 'one',
        columnReverse:                false,
        headerAlignment:              'center',
        headerArrangement:            'bullet',
        sectionHeadingStyle:          'top-bottom',
        sectionHeadingSize:           'L',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingLineThickness:  0.5,
        sectionHeadingIcon:           'none',
        nameSize:                     'XXL',
        nameBold:                     true,
        fontFamily:                   'Playfair Display',
        fontSize:                     11,
        lineHeight:                   1.5,
        marginHorizontal:             24,
        marginVertical:               20,
        entrySpacing:                 1.2,
      }
    case 'berlin':
      return {
        ...colorReset('#000000'),
        themeColorStyle:              'basic',
        applyAccentName:              true,
        applyAccentJobTitle:          false,
        applyAccentHeadings:          true,
        applyAccentHeadingLine:       true,
        applyAccentHeaderIcons:       false,
        applyAccentDotsBarsBubbles:   true,
        applyAccentDates:             false,
        applyAccentEntrySubtitle:     false,
        applyAccentLinkIcons:         true,
        columnLayout:                 'mix',
        columnReverse:                false,
        headerAlignment:              'left',
        headerArrangement:            'verticalBar',
        sectionHeadingStyle:          'background',
        sectionHeadingSize:           'S',
        sectionHeadingCapitalization: 'uppercase',
        sectionHeadingIcon:           'knockout',
        sectionHeadingIconSize:       0.8,
        nameSize:                     'XL',
        nameBold:                     true,
        fontFamily:                   'Roboto',
        fontSize:                     10,
        lineHeight:                   1.4,
        marginHorizontal:             18,
        marginVertical:               14,
        entrySpacing:                 1.0,
      }
    default:
      return {}
  }
}
