// Section component registry — static exports only
export { HeaderSection }         from './HeaderSection'
export { SummarySection }        from './SummarySection'
export { ExperienceSection }     from './ExperienceSection'
export { EducationSection }      from './EducationSection'
export { SkillsSection }         from './SkillsSection'
export { ProjectsSection }       from './ProjectsSection'
export { CertificationsSection } from './CertificationsSection'
export { LanguagesSection }      from './LanguagesSection'
export { AwardsSection }         from './AwardsSection'
export { VolunteeringSection }   from './VolunteeringSection'
export { PublicationsSection }   from './PublicationsSection'
export { ReferencesSection }     from './ReferencesSection'
export { CustomSection }         from './CustomSection'
